### PR TITLE
Make the Website Responsive for all device

### LINKED ISSUE #84: Website is not responsive for mobile device
**Describe the bug**

The website is not user friendly for mobile user as it not completely responsive.
**Expected behavior**

Some elements of the website go out of their  actual container range
**Screenshots**
If applicable, add screenshots to help explain your problem. -->
responsiveness

**Additional context(if any)**
Kindly assign me this issue i want to work in this under **apertre24**.
***Are you contributing under any open-source program ?***

Yes, Apertre24

### PR DESCRIPTION
**Pull request by rko0211**
# Title and Issue number 

Title : Make the Website Responsive for all device

Issue No. : #84 

Close #90

**Screnshots**
Website link : https://rko0211.github.io/MESSI_MANIA/

**Additional context(if any)**
KIndly review my PR and merge it under Apertre24. Thank you..

***Are you contributing under any Open-source programme?***

Apertre24

### CODE REVIEW

**Comment by Soumyajit2825** [comment]
The responsive issue is already solved! can you just modify the changes during the recent changes???
Just pull the changes and see the responsiveness you can do changes in the stats section for mobile view @rko0211

**Comment by rko0211** [comment]
Yes but at that time before merging new PR it's navbar was not responsive. That's why I did this changes..

**Comment by Soumyajit2825** [comment]
ok thanks for your contribution!

**Comment by rko0211** [comment]
Hey can i work in footer part of this website as it's content is not in right place.

**Comment by Soumyajit2825** [comment]
yeh, create another issue!

**Pull request closed without merging**
