### PR TITLE
added new photo

### PR DESCRIPTION
**Pull request by Rohan-A-V**
Hi there , please accept my pull request #hacktoberfest

### CODE REVIEW

**Comment by Soumyajit2825** [comment]
give a screen shot of your changed are!!

**Comment by Rohan-A-V** [comment]
> give a screen shot of your changed are!!

I contributed to Messi photo gallery

**Comment by Soumyajit2825** [comment]
> > give a screen shot of your changed are!!
> 
> I contributed to Messi photo gallery

Ok fine.Just go to your updated HTML web page take a screen shot and drag the file here.I just want to see the particular changes

**Comment by Rohan-A-V** [comment]
I've sent the screenshot.

**Comment by Soumyajit2825** [comment]
@Rohan-A-V give a star to this repo thank you for contributing

**Pull request merged**
