### PR TITLE
ui improvement on where is messi

### LINKED ISSUE #135: Responsiveness of worldmap Stats
**Describe the bug**

the stats are not showing on mobile phones on clicking the world map under "Where is Messi Section"

**Expected behavior**

It should display the country flag and number of goals.

**Screenshots**

**Additional context(if any)**

***Are you contributing under any open-source program ?***

Apertre

### PR DESCRIPTION
**Pull request by abhraneel2004**
#135 Responsiveness of world map stats

Title :Responsiveness of world map stats

Issue No. : #135 

Close #135

**Screnshots**

**Additional context(if any)**

***Are you contributing under any Open-source programme?***

Apertre

### CODE REVIEW

**Comment by Soumyajit2825** [comment]
@abhraneel2004 merge conflicts!

**Comment by abhraneel2004** [comment]
fixed the merge conflict.

**Comment by 5h0ov** [comment]
@abhraneel2004  can you delete the leo-raise1.png in ur repo and pull the img from this main repo? its causing conflicts

**Comment by abhraneel2004** [comment]
> @abhraneel2004 can you delete the **Image/leo-raise1.png** in ur repo and pull the img from this main repo? its causing conflicts

I have updated the image for better visibility of the world map. If it is creating a problem then please wait for my PR, don't merge a new PR before my PR. It's a request. It'll take maximum 30 mins

**Comment by 5h0ov** [comment]
> > @abhraneel2004 can you delete the **Image/leo-raise1.png** in ur repo and pull the img from this main repo? its causing conflicts
> 
> I have updated the image for better visibility of the world map. If it is creating a problem then please wait for my PR, don't merge a new PR before my PR. It's a request. It'll take maximum 30 mins

yes ok i will merge now

**Pull request merged**
