### PR TITLE
Sayan

### LINKED ISSUE #80: Feature_Request Making the navbar look cool
**Describe the feature you are requesting**
Currently the navbar looks  very cringy. I want to give it a cool look

**Additional context(if any)**

***Are you contributing under any open-source program ?***
Aperture

### PR DESCRIPTION
**Pull request by sayan-1210**
# Title and Issue number 

Title : Feature_Request Making the navbar look cool

Issue No. : #80 

Close #80 

**Screnshots**

Made the navbar responsive and nav bar will always on top 
Before:
Screenshot 2024-01-06 024422

After:
Screenshot 2024-01-06 024440

Made the word "Ballon d'or" on the left 
Before:
Screenshot 2024-01-06 024502
After:
Screenshot 2024-01-06 024524

Also added the hamburger menu icon for the nav bar for small screen users

***Are you contributing under any Open-source programme?***
Apertre

### CODE REVIEW

**Comment by Soumyajit2825** [comment]
image

@sayan-1210 Look the footer can you solve this too? If yes then do it. I will give you the hard label and will merge

**Comment by sayan-1210** [comment]
Yup done

**Comment by Soumyajit2825** [comment]
> Yup done

Ok do the changes! I will merge it in the evening!

**Comment by sayan-1210** [comment]
Made the footer responsive
Before:
Screenshot 2024-01-06 172040
After:
Screenshot 2024-01-06 172052

**Pull request merged**
