### PR TITLE
Made facts section more beautiful

### PR DESCRIPTION
**Pull request by swapn652**
This is with respect to issue #63 

image

@Soumyajit2825 please take a look and tell me if you need some more improvements.

### CODE REVIEW

**Comment by Soumyajit2825** [comment]
Can u add a background for the "Facts" 
Like these 👎🏻 
Screenshot 2022-10-17 122945

See here how the "Videos" and "Photos" section are highlighted with some colors
If you can do it then it will be good

**Comment by swapn652** [comment]
image

@Soumyajit2825 how about now? Tell me if you need some other color combinations.

**Comment by Soumyajit2825** [comment]
Yeah now ok....

**Comment by Soumyajit2825** [comment]
Now u can do the PR

**Pull request merged**
