### PR TITLE
Responsive

### LINKED ISSUE #72: Fix image size and width of the video in Responsive Web Design
Messi
Screenshot 2023-12-31 184537

### PR DESCRIPTION
**Pull request by YooAshu**
# Title and Issue number 

Title :made responsive

Issue No. :#72

Close #72 

**Screnshots**

Screenshot (69)

Screenshot (70)

Screenshot (67)
Screenshot (68)
Screenshot (66)n-source programme?***
Screenshot (65)

apertre24

### CODE REVIEW

**Comment by YooAshu** [comment]
http://asghar.tech/MESSI_MANIA/

**Comment by Soumyajit2825** [comment]
@YooAshu can you just do git pull once to solve the merge conflicts?
others are perfect!

**Comment by YooAshu** [comment]
@Soumyajit2825 pls check

**Comment by Soumyajit2825** [comment]
image

Have you checked here @YooAshu !

**Comment by YooAshu** [comment]
Oo I checked for only mobile versions

**Comment by Soumyajit2825** [comment]
image
Actually this is the mobile view itself! @YooAshu

**Comment by YooAshu** [comment]
@Soumyajit2825 i made some changes pls check

**Comment by Soumyajit2825** [comment]
> @Soumyajit2825 i made some changes pls check

already merged

**Pull request merged**
