### PR TITLE
img-show.cpp

### PR DESCRIPTION
**Pull request by Shant-singh**

### CODE REVIEW

**Comment by Soumyajit2825** [comment]
Give a ss of your changes

**Comment by Shant-singh** [comment]
sorry but ss means what?

**Comment by Soumyajit2825** [comment]
Screen shot - of your changes in the web page

**Comment by Shant-singh** [comment]
That is a cpp code so whatever address of img u provide it will show the img by running the code.it takes address of img as an input

**Comment by Soumyajit2825** [comment]
What it will help for the html page MESSI_MANIA

**Pull request closed without merging**
